server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
jwt:
  expiration: 7200
  secretKey: "L7p3X6gRHFtLJYp7v9XxWD5mMcu6uZzB4ELgkW8l2aI="

file:
  upload-dir: "F:/my workspace/Apple-shop/business-service/uploads"

  vnpay:
    tmn-code: YR1UQMDB
    secret-key: 4U06X3RP8MGFZ4QSGA9LS2VOEHK8JGJA
    vnp-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
