server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  expiration: 7200
  secretKey: "L7p3X6gRHFtLJYp7v9XxWD5mMcu6uZzB4ELgkW8l2aI="
