server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
jwt:
  expiration: 7200
  secretKey: "L7p3X6gRHFtLJYp7v9XxWD5mMcu6uZzB4ELgkW8l2aI="

file:
  upload-dir: "F:/my workspace/Apple-shop/business-service/uploads"

  vnpay:
    tmn-code: YR1UQMDB
    secret-key: 4U06X3RP8MGFZ4QSGA9LS2VOEHK8JGJA
    vnp-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

app:
  oauth2:
    providers:
      google:
        client-id: "your-google-client-id"
        client-secret: "your-google-client-secret"
        redirect-uri: "http://localhost:8080/api/v1/auth/oauth2/callback/google"
        authorization-uri: "https://accounts.google.com/o/oauth2/auth"
        token-uri: "https://oauth2.googleapis.com/token"
        user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
        scope: "email profile"
      facebook:
        client-id: "your-facebook-app-id"
        client-secret: "your-facebook-app-secret"
        redirect-uri: "http://localhost:8080/api/v1/auth/oauth2/callback/facebook"
        authorization-uri: "https://www.facebook.com/v12.0/dialog/oauth"
        token-uri: "https://graph.facebook.com/v12.0/oauth/access_token"
        user-info-uri: "https://graph.facebook.com/v12.0/me"
        scope: "email public_profile"
